name: Build and install

on:
  push:
    branches: [ "main" ]
  pull_request:
  
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v3
    - name: Install required packages  on macos
      if: matrix.os == 'macos-latest'
      run: brew install autoconf automake pkg-config
    - name: Install required packages on ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get -y install automake autoconf pkg-config
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make install on macos
      if: matrix.os == 'macos-latest'
      run: make install
    - name: make install on ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo make install
    - name: Test pkg-config setup
      run: pkg-config --libs shine
      
  android_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25b
        local-cache: true
    - name: Install autoconf/automake
      run: sudo apt-get -y install automake autoconf
    - name: bootstrap
      run: ./bootstrap
    - name: configure
      run: ./configure
    - name: make android
      run: make android   

  js_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: mymindstorm/setup-emsdk@v11
    - name: JS build
      run: |
        cd js
        make
    - uses: actions/setup-node@v3
      with:
        cache: 'npm'
    - name: Run node test
      run: |
        cd js/test/node
        npm install
        npm run test
